/* generated by build-photos.py — do not edit by hand */
window.OUR_UNIVERSE_BUILD = {"at": "2026-09-01 09:25:08", "mode": "paths", "count": 44};
window.OUR_UNIVERSE_PHOTOS = {
 "Stage 1": [
  {
   "p": "Stage 1/1_Our First Official Date.jpeg",
   "c": "Our First Official Date",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 1,
   "n": 0
  },
  {
   "p": "Stage 1/2_Our First Movie Together.jpeg",
   "c": "Our First Movie Together",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 2,
   "n": 1
  },
  {
   "p": "Stage 1/3_Our First Night Out.jpeg",
   "c": "Our First Night Out",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 3,
   "n": 2
  },
  {
   "p": "Stage 1/4_Happy Dating Phase.jpeg",
   "c": "Happy Dating Phase",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 4,
   "n": 3
  },
  {
   "p": "Stage 1/5_The Day We Decided We'll Get Married.jpeg",
   "c": "The Day We Decided We'll Get Married",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 5,
   "n": 4
  }
 ],
 "Stage 2": [
  {
   "p": "Stage 2/1_When We Ditched The World And Got Lost Into Each Other.jpeg",
   "c": "When We Ditched The World And Got Lost Into Each Other",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 1,
   "n": 0
  },
  {
   "p": "Stage 2/2_Sharing Kisses.jpeg",
   "c": "Sharing Kisses",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 2,
   "n": 1
  },
  {
   "p": "Stage 2/3_Buiding A World With Snow.jpeg",
   "c": "Buiding A World With Snow",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 3,
   "n": 2
  },
  {
   "p": "Stage 2/4_Building A World With Snow.jpeg",
   "c": "Building A World With Snow",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 4,
   "n": 3
  }
 ],
 "Stage 3": [
  {
   "p": "Stage 3/1_Our First Trip.jpeg",
   "c": "Our First Trip",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 1,
   "n": 0
  },
  {
   "p": "Stage 3/2_Your First Mehandi Look that Slayed My Heart.jpeg",
   "c": "Your First Mehandi Look that Slayed My Heart",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 2,
   "n": 1
  },
  {
   "p": "Stage 3/3_Our First Anniversary.jpeg",
   "c": "Our First Anniversary",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 3,
   "n": 2
  }
 ],
 "Stage 4": [
  {
   "p": "Stage 4/1_Workout Buddies.jpeg",
   "c": "Workout Buddies",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 1,
   "n": 0
  },
  {
   "p": "Stage 4/2_Merginf Out Lives And People.jpeg",
   "c": "Merginf Out Lives And People",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 2,
   "n": 1
  },
  {
   "p": "Stage 4/3_Merging Our Lives And People.jpeg",
   "c": "Merging Our Lives And People",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 3,
   "n": 2
  },
  {
   "p": "Stage 4/4_#Rokafied.jpeg",
   "c": "#Rokafied",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 4,
   "n": 3
  }
 ],
 "Stage 5": [
  {
   "p": "Stage 5/1_Entering Our First Home.JPG",
   "c": "Entering Our First Home",
   "d": "2024-03-11",
   "dl": "11 March 2024",
   "o": "exif",
   "x": 1,
   "n": 0
  },
  {
   "p": "Stage 5/2_Posing In Out First Home.JPG",
   "c": "Posing In Out First Home",
   "d": "2024-03-11",
   "dl": "11 March 2024",
   "o": "exif",
   "x": 2,
   "n": 1
  },
  {
   "p": "Stage 5/3_#Engaged.jpg",
   "c": "#Engaged",
   "d": "2024-03-08",
   "dl": "8 March 2024",
   "o": "exif",
   "x": 3,
   "n": 2
  },
  {
   "p": "Stage 5/4_#Sukoon.jpg",
   "c": "#Sukoon",
   "d": "2024-03-08",
   "dl": "8 March 2024",
   "o": "exif",
   "x": 4,
   "n": 3
  },
  {
   "p": "Stage 5/5_And We Did It.jpg",
   "c": "And We Did It",
   "d": "2024-03-08",
   "dl": "8 March 2024",
   "o": "exif",
   "x": 5,
   "n": 4
  },
  {
   "p": "Stage 5/6_And It Begins.jpg",
   "c": "And It Begins",
   "d": "2024-04-21",
   "dl": "21 April 2024",
   "o": "exif",
   "x": 6,
   "n": 5
  },
  {
   "p": "Stage 5/7_#FinallyMarried.jpg",
   "c": "#FinallyMarried",
   "d": "2024-04-21",
   "dl": "21 April 2024",
   "o": "exif",
   "x": 7,
   "n": 6
  },
  {
   "p": "Stage 5/8_Taking You Home Forever.jpg",
   "c": "Taking You Home Forever",
   "d": "2024-04-21",
   "dl": "21 April 2024",
   "o": "exif",
   "x": 8,
   "n": 7
  }
 ],
 "Stage 6": [
  {
   "p": "Stage 6/1_Waiting For Manan To Come Into Our Lives.jpeg",
   "c": "Waiting For Manan To Come Into Our Lives",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 1,
   "n": 0
  },
  {
   "p": "Stage 6/2_The Day, Manan Was Born.jpeg",
   "c": "The Day, Manan Was Born",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 2,
   "n": 1
  },
  {
   "p": "Stage 6/3_Manan Wondering If We'll Be Able To Do It.jpeg",
   "c": "Manan Wondering If We'll Be Able To Do It",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 3,
   "n": 2
  },
  {
   "p": "Stage 6/4_Smirky Little Cutipie.jpeg",
   "c": "Smirky Little Cutipie",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 4,
   "n": 3
  },
  {
   "p": "Stage 6/5_Manan's First Angry Look.jpeg",
   "c": "Manan's First Angry Look",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 5,
   "n": 4
  },
  {
   "p": "Stage 6/6_#Papa.jpeg",
   "c": "#Papa",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 6,
   "n": 5
  },
  {
   "p": "Stage 6/7_#Mumma.jpeg",
   "c": "#Mumma",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 7,
   "n": 6
  },
  {
   "p": "Stage 6/8_#HappyManan.jpeg",
   "c": "#HappyManan",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 8,
   "n": 7
  }
 ],
 "Stage 7": [
  {
   "p": "Stage 7/1_#BaankaChhoraChhuiMuiKudi.jpeg",
   "c": "#BaankaChhoraChhuiMuiKudi",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 1,
   "n": 0
  },
  {
   "p": "Stage 7/2_Exploring Beaches.jpeg",
   "c": "Exploring Beaches",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 2,
   "n": 1
  },
  {
   "p": "Stage 7/3_Following Adventures.jpeg",
   "c": "Following Adventures",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 3,
   "n": 2
  },
  {
   "p": "Stage 7/5_Manan's 6 Month Anniversary.jpeg",
   "c": "Manan's 6 Month Anniversary",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 5,
   "n": 3
  },
  {
   "p": "Stage 7/6_Together In Nature.jpeg",
   "c": "Together In Nature",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 6,
   "n": 4
  },
  {
   "p": "Stage 7/7_Trips With Friends.jpeg",
   "c": "Trips With Friends",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 7,
   "n": 5
  },
  {
   "p": "Stage 7/8_Manan The Thinker.jpeg",
   "c": "Manan The Thinker",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 8,
   "n": 6
  },
  {
   "p": "Stage 7/9_Love In The Nature.jpeg",
   "c": "Love In The Nature",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 9,
   "n": 7
  },
  {
   "p": "Stage 7/10_Swagger Baby.jpeg",
   "c": "Swagger Baby",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 10,
   "n": 8
  },
  {
   "p": "Stage 7/11_Kisses Forever.jpeg",
   "c": "Kisses Forever",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 11,
   "n": 9
  },
  {
   "p": "Stage 7/13_Full Of Love.jpeg",
   "c": "Full Of Love",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 13,
   "n": 10
  },
  {
   "p": "Stage 7/14_#ToGrowingTogether.jpeg",
   "c": "#ToGrowingTogether",
   "d": "2026-09-01",
   "dl": "1 September 2026",
   "o": "file",
   "x": 14,
   "n": 11
  }
 ]
};
